#ifndef SANDHYBRID_DEBUG_STATS_GLSL
#define SANDHYBRID_DEBUG_STATS_GLSL

const uint DEBUG_STAT_WORD_COUNT = 128u;

const uint STAT_ACTIVE_CELLS = 8u;
const uint STAT_STRUCTURAL_CELLS = 9u;
const uint STAT_LIQUID_CELLS = 10u;
const uint STAT_GAS_CELLS = 11u;
const uint STAT_MOVE_PAIR_TESTS = 12u;
const uint STAT_MOVE_SWAPS = 13u;
const uint STAT_BEE_MOVES = 14u;
const uint STAT_ANT_MOVES = 15u;
const uint STAT_BEETLE_MOVES = 16u;
const uint STAT_SLEEPING_TILES = 17u;
const uint STAT_ACTIVE_TILES = 18u;
const uint STAT_BEE_COUNT = 19u;
const uint STAT_QUEEN_COUNT = 20u;
const uint STAT_NEST_COUNT = 21u;
const uint STAT_FLOWER_COUNT = 22u;
const uint STAT_POLLEN_COUNT = 23u;
const uint STAT_HONEY_COUNT = 24u;
const uint STAT_ANT_COUNT = 25u;
const uint STAT_BEETLE_COUNT = 26u;
const uint STAT_HABITAT_COUNT = 27u;
const uint STAT_SIMULATION_STEP = 28u;
const uint STAT_MOVED_CELLS = 29u;
const uint STAT_SLEEPING_CHUNKS = 30u;
const uint STAT_ACTIVE_CHUNKS = 31u;
const uint STAT_MATERIAL_BASE = 32u;
const uint STAT_MACRO_TILE_MOVES = 99u;
const uint STAT_MACRO_CELL_MOVES = 100u;
const uint STAT_DIRTY_CHUNKS = 101u;
const uint STAT_CHUNK_SKIPPED_CELLS = 102u;
const uint STAT_FINE_TILES = 103u;
const uint STAT_MACRO_TILES = 104u;
const uint STAT_SETTLED_TILES = 105u;
const uint STAT_FINE_REPAIR_MOVES = 106u;
const uint STAT_PLAYER_IMPULSES = 107u;
const uint STAT_ACTOR_MOVES = 108u;
const uint STAT_GAS_EXCESS_MOVES = 109u;
const uint STAT_MACRO_GAS_TILES = 110u;
const uint STAT_MACRO_LIQUID_TILES = 111u;
const uint STAT_MEDIUM_ENCLOSED_TILES = 112u;
const uint STAT_MEDIUM_BREAKUP_TILES = 113u;
const uint STAT_CONVEYOR_MOVES = 114u;
const uint STAT_MACHINE_INPUTS = 115u;
const uint STAT_MACHINE_OUTPUTS = 116u;
const uint STAT_STRUCTURAL_COLLAPSES = 117u;
const uint STAT_VOLCANO_LAVA_OUTPUTS = 118u;
const uint STAT_VOLCANO_GAS_OUTPUTS = 119u;
const uint STAT_GAS_EDGE_ACTIVE_TILES = 120u;
const uint STAT_CHEMISTRY_CHANGES = 121u;
const uint STAT_SCOPE_CELLS = 122u;
const uint STAT_TOTAL_TILES = 123u;
const uint STAT_UNCLASSIFIED_TILES = 124u;
const uint STAT_TOTAL_CHUNKS = 125u;

#endif
